## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [1]:
import numpy as np
x=np.array([78,11,24,54,22])
np.all(x)

True

Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [2]:
import numpy as np

zeros_arr=np.zeros(10)
ones_arr=np.ones(10)
fives_arr=np.full(10,5)

Final_arr=np.concatenate((zeros_arr,ones_arr,fives_arr))

print("Final Array",Final_arr)

Final Array [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [3]:
import numpy as np
from numpy import random
x=np.random.normal(170,10,15)
print(x)

[161.02119871 185.81871934 169.42772953 159.78664753 173.78569482
 179.36540679 170.53858767 156.32585405 146.03110844 157.41416221
 177.32825791 160.60004874 194.56530875 168.51780034 174.65819446]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [4]:
import numpy as np
from numpy import random 
x=np.random.normal(200,7,(8,5))
print(x)


[[204.97562986 204.50305857 198.41384628 200.66687524 196.88457485]
 [216.02484181 213.83360511 203.02675069 209.07321968 190.85812199]
 [200.92260426 195.83904557 207.82533457 196.72439373 189.61292567]
 [199.20564869 201.2896935  204.24720753 191.98196342 197.24705851]
 [198.5621326  207.09421714 202.67577698 193.72370694 206.04062062]
 [192.72827042 204.0157563  195.6323057  197.22750675 196.93959795]
 [199.20123759 206.63336941 195.35262646 198.6941755  197.43358565]
 [205.93968477 204.00495344 197.65106962 200.28506279 189.34990499]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [5]:
import numpy as np
x=np.random.normal(10,1,(4,4))
print('Original X Array:\n',x)
swappedx=x[:,[3,2,1,0]]
print('\nSwapped X Array:\n',swappedx)

Original X Array:
 [[10.50689986 11.1748022   9.68692944 10.43244261]
 [10.6452972  10.53881689 11.82607373 10.65218878]
 [ 9.80095242  9.06444013 11.83430827  8.9195905 ]
 [11.36500955  9.47592287  8.07366884 10.58105776]]

Swapped X Array:
 [[10.43244261  9.68692944 11.1748022  10.50689986]
 [10.65218878 11.82607373 10.53881689 10.6452972 ]
 [ 8.9195905  11.83430827  9.06444013  9.80095242]
 [10.58105776  8.07366884  9.47592287 11.36500955]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [6]:
import numpy as np
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
reversed_rows = original_array[::-1]
reversed_columns = original_array[:, ::-1]
swapped_array = reversed_rows[:, ::-1]
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Swapped Array:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [7]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res = arr1 * arr2
print(res)

[[ 5 12]
 [21 32]]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [8]:
import numpy as np
values = np.arange(2, 11)
mat = values.reshape(3, 3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [9]:
import numpy as np
r = np.random.rand(3, 3, 3)
print(r)

[[[0.46451719 0.32549236 0.72711629]
  [0.84280715 0.56365098 0.21758795]
  [0.02977434 0.07360226 0.74027294]]

 [[0.87374325 0.775545   0.18105256]
  [0.91513956 0.43196685 0.20492469]
  [0.84303534 0.57733075 0.87803368]]

 [[0.46705344 0.0401205  0.80962077]
  [0.24975703 0.47967495 0.10698115]
  [0.3274454  0.65843657 0.5299691 ]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [10]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
flattened_array = array.flatten()
maxvalue = np.amax(flattened_array)
minvalue = np.amin(flattened_array)
print("Maximum value:", maxvalue)
print("Minimum value:", minvalue)

Maximum value: 9
Minimum value: 1


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [11]:
n1=np.array([1])
n2=np.array([4])
print("Add:",float(n1+n2))
print("Subtract:",float(n1-n2))
print("Multiply:",float(n1*n2))
print("Divide:",float(n1/n2))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [12]:
n1=np.array([0,1,2,3,4,5,6])
n2=np.array([3])
print(n1**n2)

[  0   1   8  27  64 125 216]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [13]:
n=np.random.randint(1,11)
s=int(input("Enter a random Number from 1 to 10:"))
if n==s:
      print("You Gussed the Correct Number")
else:
      print("you Guessed the wrong number. The random number is:"+str(n))

Enter a random Number from 1 to 10:1
you Guessed the wrong number. The random number is:3


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [14]:
import numpy as np
rows, cols = 5, 5
array = np.zeros((rows, cols))
array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1 
print("array:")
print(array.astype(int))

array:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [15]:
arr=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr=np.append(arr,arr2)
print(arr)

[10 20 30 40 50 60 70 80 90]
